# Generated by Django 5.0.2 on 2025-11-30 08:30

import apps.users.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_employer_expansion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravellerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('timesheet_pdf', 'Timesheet PDF'), ('payslip_pdf', 'Payslip PDF'), ('compliance_image', 'Compliance Image'), ('other', 'Other')], default='other', max_length=32)),
                ('file', models.FileField(upload_to=apps.users.models.traveller_document_upload_to)),
                ('mime_type', models.CharField(blank=True, max_length=64)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('source_type', models.CharField(blank=True, max_length=32)),
                ('source_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
