# Generated by Django 5.0.2 on 2025-12-01 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_travellerdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='superannuation_account_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='superannuation_fund_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='travellerdocument',
            name='category',
            field=models.CharField(choices=[('timesheet_pdf', 'Timesheet PDF'), ('payslip_pdf', 'Payslip PDF'), ('payslip_aba', 'Payslip ABA'), ('compliance_image', 'Compliance Image'), ('other', 'Other')], default='other', max_length=32),
        ),
    ]
