# Generated by Django 5.0.2 on 2025-12-01 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_superannuation_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
    ]
