# Generated by Django 5.0.2 on 2025-11-30 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_timesheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheetentry',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
