# Generated by Django 5.0.2 on 2025-11-30 04:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_timesheetentry_is_locked_alter_timesheet_id_and_more'),
        ('users', '0004_employer_expansion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheetentry',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timesheetentry',
            name='payment_status',
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("instructions_generated", "Instructions Generated"),
                    ("awaiting_bank_import", "Awaiting Bank Import"),
                    ("paid", "Paid"),
                ],
                default="pending",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_count', models.DecimalField(decimal_places=2, max_digits=7)),
                ('rate_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('rate_currency', models.CharField(default='AUD', max_length=5)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_before_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_withheld', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='users.employer')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='applications.joboffer')),
                ('timesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='applications.timesheet')),
                ('traveller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
