# Generated by Django 5.0.2 on 2025-11-30 09:16

import apps.applications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_timesheetentry_is_paid_payslip'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='employer_abn',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='payslip',
            name='employer_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='payslip',
            name='employer_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='payslip',
            name='pay_period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='pay_period_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='payment_method',
            field=models.CharField(default='bank_transfer', max_length=32),
        ),
        migrations.AddField(
            model_name='payslip',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to=apps.applications.models.payslip_pdf_upload_to),
        ),
        migrations.AddField(
            model_name='payslip',
            name='super_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payslip',
            name='traveller_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='payslip',
            name='traveller_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='payslip',
            name='traveller_tfn',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
