# Generated by Django 5.0.2 on 2025-12-01 00:06

import apps.applications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_payslip_employer_abn_payslip_employer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='aba_file',
            field=models.FileField(blank=True, upload_to=apps.applications.models.payslip_aba_upload_to),
        ),
        migrations.AddField(
            model_name='payslip',
            name='aba_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='aba_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='payslip',
            name='instructions_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('instructions_generated', 'Instructions Generated'), ('awaiting_bank_import', 'Awaiting Bank Import'), ('completed', 'Completed')], default='pending', max_length=32),
        ),
    ]
