# Generated by Cascade on 2025-12-01
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0008_payslip_aba_file_payslip_aba_generated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="timesheetentry",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("instructions_generated", "Instructions Generated"),
                    ("awaiting_bank_import", "Awaiting Bank Import"),
                    ("paid", "Paid"),
                ],
                default="pending",
                max_length=32,
            ),
        ),
    ]
