# Generated by Django 5.0.2 on 2025-12-01 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_add_timesheet_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='last_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
